package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/PuerkitoBio/goquery"
	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
	"google.golang.org/api/calendar/v3"
	"google.golang.org/api/option"
)

func get_document(url string) goquery.Selection {
	resp, err := http.Get(url)
	if err != nil {
		log.Fatalf("Unable to retrieve schedule page web: %v",err)
	}

	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		log.Fatalf("status code error: %d %s", resp.StatusCode, resp.Status)
	}

	doc, err := goquery.NewDocumentFromReader(resp.Body)
	if err != nil {
		log.Fatalf("Unable to parse a doc: %v", err)
	}
	return *doc.Find(".q_tabs").First()
}

func get_scene_list(doc goquery.Selection) []string {
	scene_html_list := doc.Find(".timeline-stages").First().Children()
	scene_list := make([]string, scene_html_list.Size())

	scene_html_list.Each(func(i int, s *goquery.Selection) {
		scene_list[i] = s.Text()
	})
	return scene_list
}

func get_show_list(doc goquery.Selection, scene_list []string) []Show {
	result := make([]Show, 0)
	doc.Find(".timeline-lists").Each(func(i int, day_block *goquery.Selection) {
		day_block.Find(".list").Each(func(scene_num int, scene_block *goquery.Selection) {
			scene := scene_list[scene_num]
			scene_block.Children().Children().Each(func(i int, show *goquery.Selection) {
				name := show.Text()
				start_date, _ := show.Attr("data-start")
				start_date64, _ := strconv.ParseInt(start_date, 10, 64)
				end_date, _ := show.Attr("data-end")
				end_date64, _ := strconv.ParseInt(end_date, 10, 64)
				url, _ := show.Attr("href")
				result = append(result, Show{scene, strconv.Itoa(scene_num), strings.Trim(name, " "), start_date64, end_date64, url})
			})
		})
	})
	return result
}

// Retrieve a token, saves the token, then returns the generated client.
func getClient(config *oauth2.Config) *http.Client {
	// The file token.json stores the user's access and refresh tokens, and is
	// created automatically when the authorization flow completes for the first
	// time.
	tokFile := "../../token.json"
	tok, err := tokenFromFile(tokFile)
	if err != nil {
		tok = getTokenFromWeb(config)
		saveToken(tokFile, tok)
	}
	return config.Client(context.Background(), tok)
}

// Retrieves a token from a local file.
func tokenFromFile(file string) (*oauth2.Token, error) {
	f, err := os.Open(file)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	tok := &oauth2.Token{}
	err = json.NewDecoder(f).Decode(tok)
	return tok, err
}

// Request a token from the web, then returns the retrieved token.
func getTokenFromWeb(config *oauth2.Config) *oauth2.Token {
	authURL := config.AuthCodeURL("state-token", oauth2.AccessTypeOffline)
	fmt.Printf("Go to the following link in your browser then type the "+
		"authorization code: \n%v\n", authURL)

	var authCode string
	if _, err := fmt.Scan(&authCode); err != nil {
		log.Fatalf("Unable to read authorization code: %v", err)
	}

	tok, err := config.Exchange(context.TODO(), authCode)
	if err != nil {
		log.Fatalf("Unable to retrieve token from web: %v", err)
	}
	return tok
}

// Saves a token to a file path.
func saveToken(path string, token *oauth2.Token) {
	fmt.Printf("Saving credential file to: %s\n", path)
	f, err := os.OpenFile(path, os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		log.Fatalf("Unable to cache oauth token: %v", err)
	}
	defer f.Close()
	json.NewEncoder(f).Encode(token)
}

func get_or_create_calendar(svc calendar.Service) *calendar.Calendar {
	list, err := svc.CalendarList.List().Do()
	if err != nil {
		log.Fatalf("Unable to retrieve Calendar list: %v", err)
	}
	cal_id := ""
	for i := 0; i < len(list.Items); i++ {
		cal := list.Items[i]
		if cal.Summary == "ZaxidFest_auto" {
			cal_id = cal.Id
			break
		}
	}
	if cal_id == "" {
		cal := calendar.Calendar{Summary: "ZaxidFest_auto", TimeZone: "Europe/Kiev", Description: "Autogenerated calendar. Source: https://zaxidfest.com/schedule/"}
		res, err := svc.Calendars.Insert(&cal).Do()
		if err != nil {
			log.Fatalf("Unable to insert a new calendar: %v", err)
		}
		return res
	} else {
		cal, err := svc.Calendars.Get(cal_id).Do()
		if err != nil {
			log.Fatalf("Unable to get a calendar: %v", err)
		}
		return cal
	}
}

func cleanup_calendar(svc calendar.Service, cal calendar.Calendar) {
	events, err := svc.Events.List(cal.Id).Do()
	if err != nil {
		log.Fatalf("Unable to retrieve Event list: %v", err)
	}
	for i := 0; i < len(events.Items); i++ {
		svc.Events.Delete(cal.Id, events.Items[i].Id).Do()
		time.Sleep(100 * time.Millisecond)
	}

}

func populate_calendar(svc calendar.Service, cal calendar.Calendar, show_list []Show) {
	for i := 0; i < len(show_list); i++ {
		show := show_list[i]
		event := calendar.Event{
			Summary:  show.name,
			Location: show.scene,
			ColorId:  show.scene_num,
			Start: &calendar.EventDateTime{
				DateTime: time.Unix(show.start_date, 0).Format(time.RFC3339),
			},
			End: &calendar.EventDateTime{
				DateTime: time.Unix(show.end_date, 0).Format(time.RFC3339),
			},
			Description: show.url,
		}
		_, err := svc.Events.Insert(cal.Id, &event).Do()
		if err != nil {
			log.Fatalf("Unable to create an event: %v", err)
		}
		time.Sleep(100 * time.Millisecond)
	}
}

func do_calendar_stuff(show_list []Show) {
	ctx := context.Background()
	// Authorization credentials for a desktop application. To learn how to create credentials for a desktop application, refer to Create credentials.
	// https://developers.google.com/workspace/guides/create-credentials
	b, err := ioutil.ReadFile("../../credentials.json")
	if err != nil {
		log.Fatalf("Unable to read client secret file: %v", err)
	}
	// If modifying these scopes, delete your previously saved token.json.
	config, err := google.ConfigFromJSON(b, calendar.CalendarScope)
	if err != nil {
		log.Fatalf("Unable to parse client secret file to config: %v", err)
	}
	client := getClient(config)
	srv, err := calendar.NewService(ctx, option.WithHTTPClient(client))
	if err != nil {
		log.Fatalf("Unable to retrieve Calendar client: %v", err)
	}
	cal := get_or_create_calendar(*srv)
	cleanup_calendar(*srv, *cal)
	populate_calendar(*srv, *cal, show_list)
}

func main() {
	doc := get_document("https://zaxidfest.com/schedule/")
	scene_list := get_scene_list(doc)
	show_list := get_show_list(doc, scene_list)
	do_calendar_stuff(show_list)

}

type Show struct {
	scene      string
	scene_num  string
	name       string
	start_date int64
	end_date   int64
	url        string
}
