package main

import (
	"github.com/PuerkitoBio/goquery"
)

func main() {
	// fetch docs from graspop website
	// they use separate pages for each day
	docs := [...]goquery.Selection{
		get_document("https://www.graspop.be/en/line-up/schedule/thursday/"),
		get_document("https://www.graspop.be/en/line-up/schedule/friday/"),
		get_document("https://www.graspop.be/en/line-up/schedule/saturday/"),
		get_document("https://www.graspop.be/en/line-up/schedule/sunday/")}
	// get list of scenes. it's the same for all days so let's pick 0th
	stages := getStagesList(docs[0])

	showList := getShowList(docs, stages, 16, 6, 2022, "Europe/Brussels")

	uploadToGoogleCalendar(showList, "credentials.json", "token.json",
		"Graspop_auto", "Europe/Brussels", "Autogenerated calendar. Source: https://www.graspop.be/en/line-up/schedule/")
}
